site_name: aiosql docs
site_description: Simple SQL in Python
site_author: William Vaughn
copyright: Copyright 2018-2020, William Vaughn
site_url: https://nackjicholson.github.io/aiosql/
repo_url: https://github.com/nackjicholson/aiosql/
theme: readthedocs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Defining SQL Queries: defining-sql-queries.md
  - Advanced Topics: advanced-topics.md
  - Database Driver Adapters: database-driver-adapters.md
  - API: api.md
markdown_extensions:
- admonition
- footnotes
- mkautodoc
- toc:
    permalink: true
extra_css:
    - css/custom.css
