site_name: aiosql docs
site_description: Simple SQL in Python
site_author: William Vaughn
copyright: Copyright 2018-2020, William Vaughn
site_url: https://nackjicholson.github.io/aiosql/
repo_url: https://github.com/nackjicholson/aiosql/
theme: readthedocs
nav:
  - Usage: index.md
  - Defining SQL Queries: defining-sql-queries.md
  - Using SQL in Python: using-sql-in-python.md
  - Advanced Topics: advanced-topics.md
  - Database Driver Adapters: database-driver-adapters.md
markdown_extensions:
- admonition
- footnotes
- toc:
    permalink: true
