FROM ubuntu
LABEL description="Python setup for AioSQL Postgres testing"
RUN apt update
RUN apt install -y --no-install-recommends \
      python-is-python3 python3-venv python3-dev gcc make curl pkg-config
RUN python -m venv /venv
RUN /venv/bin/pip install asyncio pytest pytest-asyncio coverage
WORKDIR /code
# postgres specific packages
RUN apt install -y --no-install-recommends libpq-dev
RUN apt clean
RUN /venv/bin/pip install psycopg psycopg2 pygresql pg8000 asyncpg pytest-postgresql
