#
# Docker containers to test aiosql against various databases
#
# TEST is either "pytest" or "coverage"
#

name: aiosql-tests

services:
  #
  # postgres tests
  #
  postgres-server:
    image: postgres
    environment:
      - POSTGRES_DB=pytest
      - POSTGRES_USER=pytest
      - POSTGRES_PASSWORD=pytest
  pg-client:
    image: python-aiosql-postgres
    volumes:
      - ..:/code
    depends_on:
      - postgres-server
    environment:
      - PG_HOST=postgres-server
      - PG_PORT=5432
    command: make VENV=/venv check.$TEST.postgres.detached
  #
  # mysql tests
  #
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pytest
      - MYSQL_USER=pytest
      - MYSQL_PASSWORD=pytest
      - MYSQL_DATABASE=pytest
  my-client:
    image: python-aiosql-mysql
    depends_on:
      - mysql-server
    volumes:
      - ..:/code
    environment:
      - MY_HOST=mysql-server
      - MY_PORT=3306
    command: make VENV=/venv check.$TEST.mysql.detached
  #
  # other tests
  #
  mariadb-server:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=pytest
      - MYSQL_USER=pytest
      - MYSQL_PASSWORD=pytest
      - MYSQL_DATABASE=pytest
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1433
      - MSSQL_SA_PASSWORD=Abc123..
      - MSSQL_PID=Developer
  dbs-client:
    image: python-aiosql-dbs
    depends_on:
      - mariadb-server
      - mssql-server
    volumes:
      - ..:/code
    environment:
      - MA_HOST=mariadb-server
      - MA_PORT=3306
      - MS_HOST=mssql-server
      - MS_PORT=1433
      - MS_PASS=Abc123..
    command: >
      make VENV=/venv check.$TEST.mariadb.detached check.$TEST.mssql.detached check.$TEST.misc
