LABEL description="Python AioSQL setup for Postgres"
FROM ubuntu
RUN apt update
RUN apt install -y --no-install-recommends \
      python-is-python3 python3-venv python3-dev gcc make curl
RUN python -m venv /venv
RUN /venv/bin/pip install asyncio pytest pytest-asyncio coverage
WORKDIR /code
# postgres specific
RUN apt install -y --no-install-recommends libpq-dev sqlite3
RUN apt clean
RUN /venv/bin/pip install psycopg psycopg2 pygresql pg8000 asyncpg pytest-postgresql apsw aiosqlite
