FROM ubuntu
RUN apt update
RUN apt install -y --no-install-recommends \
      python-is-python3 python3-venv python3-dev gcc make
RUN python -m venv /venv
RUN /venv/bin/pip install asyncio pytest pytest-asyncio coverage
WORKDIR /code
# mariadb specific
RUN apt install -y --no-install-recommends libmariadb-dev
RUN apt clean
RUN /venv/bin/pip install mariadb pytest-mysql
